version: '3'

services:
  app:
    build:
      context: ../../
      dockerfile: infra/dev/Dockerfile
    volumes:
      - ../../:/code
    ports:
      - "3000:3000"
  redis:
    image: "redis:alpine"
